name: Build BBCSDL linux 64 bit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-ttf-dev
        sudo apt-get install libsdl2-net-dev
        sudo apt-get install libsdl2-2.0-0
        sudo apt-get install libsdl2-ttf-2.0-0
        sudo apt-get install libsdl2-net-2.0-0
        sudo apt-get install nasm
        
    - name: make
      run: |
        cd bin/linux
        make
        
    - name: 'Tar files'
      run: |
        tar -cvf bbcsdl.tar bbcsdl libstb.so Box2D231.so

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: bbcsdl
        path: bbcsdl.tar    
      
