name: Build BBCSDL linux 64 bit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-net-dev libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-net-2.0-0 nasm
        
    - name: make
      run: |
        cd bin/linux
        make

    - name: Copy readme etc
      run: |
        cp bin/linux/install64.txt .
        
              
    - name: 'Tar files'
      run: |
        tar -cvfz bbcsdl.tgz bbcsdl libstb.so install64.txt lib bbcsdl.bbc examples licence.txt

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: bbcsdl
        path: bbcsdl.tgz    
      
